config/routes.rb
Rails.application.routes.draw do
  #api
  mount API::Wechats => '/api'

  constraints(SubdomainRoutes) do 
    root "homepages#index"
  end 

  constraints(!SubdomainRoutes) do
    root 'welcomes#show'
    get 'echo', to: "welcomes#feedback", as: :echo
    get 'present', to: "welcomes#introduction", as: :present
    get 'release', to: "welcomes#article", as: :release
    get 'release/:id', to: "welcomes#press", as: :press
    get 'product', to: "welcomes#service", as: :product
    get 'serve/:id', to: "welcomes#serve", as: :serve
    get 'apply', to: "welcomes#recruit", as: :apply
    get 'invite/:id', to: "welcomes#invite", as: :invite
    get 'plat', to: "welcomes#map", as: :plat
    get 'picture', to: "welcomes#photograph", as: :picture
    get 'staff', to: "welcomes#employee", as: :staff
  end

  resources :admins do
    get 'delete', on: :member
    get 'privileges', on: :member
    put 'update_privilege', on: :member
    get 'search', on: :collection
  end

  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :employees do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end

  resources :carousels do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
    get 'attributes_reveal', on: :member
  end

  resources :contacts, :introductions, :articles, :services, :recruits do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end 

  resources :feedbacks do
    get 'delete', on: :member
  end
  
  resources :navbars do 
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'color', on: :collection
    put 'set_color', on: :collection
    get 'position', on: :collection
    put 'set_position', on: :collection
    get 'modify', on: :collection
    put 'set_modify', on: :collection
    get 'order', on: :collection
    put 'sort', on: :collection
  end

  resources :basics do
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'contact', on: :collection
    put 'set_contact', on: :collection
    get 'map_position', on: :collection
    put 'set_map_position', on: :collection
    get 'map_height', on: :collection
    put 'set_map_height', on: :collection
    put 'set_small_map', on: :collection
  end
  
  resources :options do 
    get 'set_reveal', on: :member
  end

  resources :maps do
    get 'delete', on: :member
    get 'set_weight', on: :member
  end

  resources :photographs do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end
    
  resources :pictures, only: [:create]
  get 'kind/:id', to: "welcomes#kind", as: :kind
  resources :logos do
    get 'reveal', on: :member
  end
end

app/models/basic.rb
class Basic < ApplicationRecord
  belongs_to :user, optional: true
  mount_uploader :logo, BasicLogoUploader

  module Status
    On = true
    Off = false
  end
end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_basic
  before_action :set_left_bar, only: [:update, :index]
  
  def index
  end  

  def update
    if @basic.update_attributes(basic_params)
      flash[:success] = "更新成功"
      redirect_to basics_path
    else 
      render 'index'
    end
  end

  def background
  end

  def set_background
    @basic.background = params[:basic][:background]
    @basic.save
    flash[:success] = "设置成功"
    redirect_to background_basics_path
  end

  def contact
    @map = current_user.maps.first
    @basic_contact = current_user.basic.contact
  end

  def set_contact
    @basic.contact = params[:basic][:contact]
    @basic.save
    flash[:success] = "设置成功"
    redirect_to contact_basics_path
  end 

  def map_position
  end

  def set_map_position
    @basic.map_position = params[:basic][:map_position]
    @basic.save
    flash[:success] = "设置成功"
    redirect_to map_position_basics_path
  end 

  def map_height
  end

  def set_map_height
    @basic.map_height = params[:basic][:map_height]
    @basic.save
    flash[:success] = "设置成功"
    redirect_to map_height_basics_path
  end 

  def set_small_map
    @basic.small_map = params[:basic][:small_map]
    @basic.save
    flash[:success] = "设置成功"
    redirect_to contact_basics_path
  end  
 
  private
    def set_basic
      @basic = current_user.basic
    end

    def basic_params
      params.require(:basic).permit(:name, :keywords, :description, :is_name)
    end

    def set_left_bar
      @available_roles = current_user.roles.reject{ |role| (role == :user) || (role == :root_admin) }.map(&:to_s)
      @options = current_user.options.where(name: @available_roles).where(reveal: true).order(:position)
    end
end

app/views/basics/_basic.html.erb
<%= form_for(@basic, url: basic_path(@basic), method: :put) do |f| %>
  <div class="form-group">
    <label>输入网站名称:</label>
    <%= f.text_field :name, placeholder: "输入网站名称", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>输入网站关键词:</label>
    <%= f.text_area :keywords, placeholder: "输入网站关键词", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>输入网站描述:</label>
    <%= f.text_area :description, placeholder: "输入网站描述", class: "form-control" %>
  </div>
  <div class="form-group">
    <select name="basic[is_name]", class="form-control">
      <% [[Basic::Status::On, "显示网站名称"], [Basic::Status::Off, "隐藏网站名称"]].each do |row| %>
        <option value="<%= row.first %>" <%= 'selected' if @basic.is_name == row.first %>><%= row.last %></option>
      <% end -%>
    </select>
  </div>
  <div class="form-group">
    <%= f.submit "更新", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/basics/background.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/style_left_bar' %></div>
  <div class="card col-md-9">
    <div class="card-body">
      <%= form_for(@basic, url: set_background_basics_path(@basic), method: :put ) do |f| %>
        <div class="form-group">
          <% ["bg-primary", "bg-secondary", "bg-success", "bg-danger", "bg-warning", "bg-info", "bg-light", "bg-dark", "bg-white"].each do |background| %>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="basic[background]"  value="<%= background %>"  <%= @basic.background == "#{background}" ? "checked" : ""%>>
              <label class="form-check-label <%= background %>">
                &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              </label>
            </div>
          <% end -%>
        </div>
        <div class="form-group">
          <%= f.submit "更新", class: "btn btn-primary"%>
        </div>
      <% end -%>
    </div>
  </div>
  </div>
</div>

app/views/basics/contact.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/style_left_bar' %></div>
  <div class="card col-md-9">
    <div class="card-body">
      <%= form_for(@basic, url: set_contact_basics_path(@basic), method: :put ) do |f| %>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[contact]"  value=""  <%= @basic.contact == "" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              不显示
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[contact]"  value="left" <%= @basic.contact == "left" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              放置在左边
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[contact]"  value="right" <%= @basic.contact == "right" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              放置在右边
            </label>
          </div>
        </div> 
        <div class="form-group">
          <%= f.submit "更新", class: "btn btn-primary"%>
        </div>
      <% end -%>
      <% if (@map && (@basic_contact != ""))  %>
        <%= form_for(@basic, url: set_small_map_basics_path(@basic), method: :put ) do |f| %>
          <div class="form-group">
            <div class="form-check">
              <input class="form-check-input" type="radio" name="basic[small_map]"  value=true  <%= @basic.small_map == true ? "checked" : ""%>>
              <label class="form-check-label text-secondary">
                显示联系栏地图
              </label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="basic[small_map]"  value=false <%= @basic.small_map == false ? "checked" : ""%>>
              <label class="form-check-label text-secondary">
                不显示联系栏地图
              </label>
            </div>
          </div>
          <div class="form-group">
            <%= f.submit "更新", class: "btn btn-primary"%>
          </div>
        <% end -%>
      <% end -%>
    </div>
  </div>
  </div>
</div>

app/views/basics/index.html.erb
<% unless current_user.has_role?(:root_admin) %>
  <%= render 'shared/nav' %>
<% end -%>
<div class="row">
  <div class="col-md-3"><%= render 'shared/left_bar' %></div>
  <div class="col-md-9">
    <%= render 'basic' %>
  </div>
</div>

app/views/basics/map.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/style_left_bar' %></div>
  <div class="card col-md-9">
    <div class="card-body">
      <%= form_for(@basic, url: set_map_basics_path(@basic), method: :put ) do |f| %>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[map]"  value=""  <%= @basic.map == "" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              不显示
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[map]"  value="left" <%= @basic.map == "left" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              放置在左边
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[map]"  value="right" <%= @basic.map == "right" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              放置在右边
            </label>
          </div>
        </div> 
        <div class="form-group">
          <%= f.submit "更新", class: "btn btn-primary"%>
        </div>
      <% end -%>
    </div>
  </div>
  </div>
</div>

app/views/basics/map_height.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/style_left_bar' %></div>
  <div class="card col-md-9">
    <div class="card-body">
      <%= form_for(@basic, url: set_map_height_basics_path(@basic), method: :put ) do |f| %>
        <div class="form-group">
          <%= f.number_field :map_height, class: "form-control" %>
        </div> 
        <div class="form-group">
          <%= f.submit "更新", class: "btn btn-primary"%>
        </div>
      <% end -%>
    </div>
  </div>
  </div>
</div>

app/views/basics/map_position.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/style_left_bar' %></div>
  <div class="card col-md-9">
    <div class="card-body">
      <%= form_for(@basic, url: set_map_position_basics_path(@basic), method: :put ) do |f| %>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[map_position]"  value=""  <%= @basic.map_position == "" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              不显示
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[map_position]"  value="left" <%= @basic.map_position == "left" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              放置在左边
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="basic[map_position]"  value="right" <%= @basic.map_position == "right" ? "checked" : ""%>>
            <label class="form-check-label text-secondary">
              放置在右边
            </label>
          </div>
        </div> 
        <div class="form-group">
          <%= f.submit "更新", class: "btn btn-primary"%>
        </div>
      <% end -%>
    </div>
  </div>
  </div>
</div>