config/routes.rb
Rails.application.routes.draw do
  #api
  mount API::Wechats => '/api'

  constraints(SubdomainRoutes) do 
    root "homepages#index"
  end 

  constraints(!SubdomainRoutes) do
    root 'welcomes#show'
    get 'echo', to: "welcomes#feedback", as: :echo
    get 'present', to: "welcomes#introduction", as: :present
    get 'release', to: "welcomes#article", as: :release
    get 'release/:id', to: "welcomes#press", as: :press
    get 'product', to: "welcomes#service", as: :product
    get 'serve/:id', to: "welcomes#serve", as: :serve
    get 'apply', to: "welcomes#recruit", as: :apply
    get 'invite/:id', to: "welcomes#invite", as: :invite
    get 'plat', to: "welcomes#map", as: :plat
    get 'picture', to: "welcomes#photograph", as: :picture
    get 'staff', to: "welcomes#employee", as: :staff
  end

  resources :admins do
    get 'delete', on: :member
    get 'privileges', on: :member
    put 'update_privilege', on: :member
    get 'search', on: :collection
  end

  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :employees do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end

  resources :carousels do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
    get 'attributes_reveal', on: :member
  end

  resources :contacts, :introductions, :articles, :services, :recruits do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end 

  resources :feedbacks do
    get 'delete', on: :member
  end
  
  resources :navbars do 
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'color', on: :collection
    put 'set_color', on: :collection
    get 'position', on: :collection
    put 'set_position', on: :collection
    get 'modify', on: :collection
    put 'set_modify', on: :collection
    get 'order', on: :collection
    put 'sort', on: :collection
  end

  resources :basics do
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'contact', on: :collection
    put 'set_contact', on: :collection
    get 'map_position', on: :collection
    put 'set_map_position', on: :collection
    get 'map_height', on: :collection
    put 'set_map_height', on: :collection
    put 'set_small_map', on: :collection
  end
  
  resources :options do 
    get 'set_reveal', on: :member
  end

  resources :maps do
    get 'delete', on: :member
    get 'set_weight', on: :member
  end

  resources :photographs do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end
    
  resources :pictures, only: [:create]
  get 'kind/:id', to: "welcomes#kind", as: :kind
  resources :logos do
    get 'reveal', on: :member
  end
end

app/views/shared/_confirm_modal.html.erb
<div class="modal fade" id="confirm-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body text-secondary">
        确定删除这条记录么?
      </div>
      <div class="modal-footer" id="confirm-modal-footer"></div>
    </div>
  </div>
</div>

app/views/shared/_contact.html.erb
<div class="card">
  <div class="card-body">
    <% if (@show_user.has_role?(:contact) && @contact) %>
      <div class="d-flex flex-column">
        <% if (@contact.is_telephone? && @contact.telephone) %>
          <div class="text-center"><i class="fa fa-phone fa-lg"></i>  <%= @contact.telephone %></div>
        <% end -%>
        <% if (@contact.is_address? && @contact.address) %>
          <div class="text-center"><i class="fa fa-map-marker fa-lg"></i>  <%= @contact.address %></div>
        <% end -%>
        <% if (@contact.is_wechat? && (@contact.wechat.size != 0)) %>
          <div class="text-center"><i class="fa fa-wechat fa-lg"></i></div>
          <%= image_tag @contact.wechat_url, class: "card-img-top" %>
        <% end -%>
        <% if (@map && (action_name != 'map') && @basic_small_map) %>
          <%= render 'shared/small_map' %>
        <% end -%>
      </div>
    <% end -%>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |type, message| %>
      <% type = type.to_s.gsub('danger', 'error').gsub('success', 'success').gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= message %>', '',
        {"closeButton": false,
         "debug": false,
         "newestOnTop": false,
         "progressBar": false,
         "positionClass": "toast-top-center",
         "preventDuplicates": false,
         "onclick": null,
         "showDuration": "100",
         "hideDuration": "1000",
         "timeOut": "1000",
         "extendedTimeOut": "1000",
         "showEasing": "swing",
         "hideEasing": "linear",
         "showMethod": "fadeIn" });
    <% end %>
  </script>
<% end %>

app/views/shared/_form_modal.html.erb
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="form-modal-title">Modal title</h5>
      </div>
      <div class="modal-body" id="form-modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="form-modal-save-btn">
          保存
        </button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_index_lists.html.erb
<div class="nav-scroller bg-white box-shadow">
  <nav class="nav nav-underline">
     <% @tags.each do |tag| %>
       <%= link_to tag.name, kind_path(tag), class: "nav-link" %>
     <% end -%>
  </nav>
</div>

app/views/shared/_left_bar.html.erb
<div class="card">
  <div class="card-body d-flex flex-column">
    <div class="mt-2">
      <%= link_to "推广设置", basics_path, class: "btn #{ (controller_name == 'basics') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block"%>
    </div> 
    <div class="mt-2">
      <%= link_to "Logo设置", new_logo_path, class: "btn #{ (controller_name == 'logos') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block" %>
    </div>
    <% @options.pluck(:name, :show).map{|option| [option[0]+"s", option[1]]}.each do |option| %>
      <div class="mt-2">
        <%= link_to "#{option.last}", { controller: "#{option.first}", action: "index"}, class: "btn #{ (controller_name == option.first) ? 'btn-primary' : 'btn-outline-secondary'} btn-block" %>
      </div>
    <% end -%>
  </div>
</div>

app/views/shared/_nav.html.erb
<ul class="nav justify-content-center mb-3">
  <li class="nav-item">
    <%= link_to "显示设置", options_path, class: "nav-link #{ ( (controller_name =='options') && (action_name == 'index')) ? 'actived' : 'disabled' }" %>
  </li>
  <li class="nav-item">
    <%= link_to "内容设置", basics_path, class: "nav-link #{ ((controller_name != 'options') && (controller_name != 'navbars') && 
    (action_name != 'background') && (action_name != 'contact') && (action_name != 'map') && (action_name != 'map_height')
    ) ? 'actived' : 'disabled' }" %>
  </li> 
  <li class="nav-item">
    <%= link_to "导航栏设置", order_navbars_path, class: "nav-link #{ ((action_name == 'order') || (action_name == 'modify') || (action_name == 'position')) ? 'actived' : 'disabled' }" %>
  </li>
  <li class="nav-item">
    <%= link_to "样式设置", background_navbars_path, class: "nav-link #{ ((action_name == 'map_height') || (action_name == 'contact') || (action_name == 'background') || (action_name == 'map') || (action_name == 'color')) ? 'actived' : 'disabled' }" %>
  </li>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light mb-1">
  <div class="container">
    <% if user_signed_in? %>
      <% if ( current_user.basic && current_user.basic.is_name? ) %>
        <%= link_to current_user.basic.name, root_path, class: "navbar-brand" %>
      <% end -%>
      <% if ( current_user.logo && current_user.logo.reveal? && (current_user.logo.name.size != 0)) %>
        <%= image_tag current_user.logo.name.url(:large), height: "50", class: "rounded"%>
      <% end -%>
    <% end -%>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle navbar-avatar" data-toggle="dropdown">
                <%= current_user.email.split("@").first %>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <%= link_to "个人设置", edit_user_registration_path, class: "dropdown-item" %>
                <% unless current_user.has_roles?(:root_admin) %>
                  <%= link_to "系统设置", options_path, class: "dropdown-item" %>
                <% end -%>
                <% if current_user.has_roles?(:root_admin) %>
                  <%= link_to "用户管理", admins_path, class: "dropdown-item" %>
                  <%= link_to "主页管理", basics_path, class: "dropdown-item" %>
                <% end -%>
                <div class="dropdown-divider"></div>
                <% unless current_user.has_roles?(:root_admin) %>
                  <%= link_to "显示页面", root_url(subdomain: current_user.subdomain), target: "_blank", class: "dropdown-item" %>
                <% end -%>
                <%= link_to "退出", destroy_user_session_path, method: "delete", class: "dropdown-item" %>
              </div>
            </li>
          <% end -%>
        </ul>
      </div>
  </div>
</nav>

app/views/shared/_navbar_left_bar.html.erb
<div class="card">
  <div class="card-body d-flex flex-column">
    <div class="mt-2">
      <%= link_to "导航栏排序", order_navbars_path, class: "btn #{ (action_name == 'order') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block" %>
    </div>
    <div class="mt-2">
      <%= link_to "导航栏修改", modify_navbars_path, class: "btn #{ (action_name == 'modify') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block" %>
    </div>
    <div class="mt-2">
      <%= link_to "导航栏位置", position_navbars_path, class: "btn #{ (controller_name == 'navbars' && action_name == 'position') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block" %>
    </div>
  </div>
</div>

app/views/shared/_official_lists.html.erb
<div class="nav-scroller bg-white box-shadow">
  <nav class="nav nav-underline">
    <%= link_to "首页", root_path, class: "nav-link" %>
    <% @options.each do |option| %>
      <% unless (option.name == "carousel" || option.name == "basic" || option.name == "contact") %>
        <%= link_to "#{option.show}", {controller: "welcomes", action: "#{option.name}"}, class: "nav-link #{action_name == option.name ? "active" : ""}" %>
      <% end -%>
    <% end -%>
  </nav>
</div>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/shared/_show_middle.html.erb
<% if @navbar_position == "middle" %>
  <%= render 'shared/official_lists' %>
<% end -%>
<% if (@show_user.has_role?(:carousel) && @carousels && @carousel_option) %>
  <%= render 'shared/carousels' %>
<% end -%>
<% if @navbar_position == "bottom" %>
  <%= render 'shared/official_lists' %>
<% end -%>

app/views/shared/_show_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light <%= @background %> <%= @color %> mb-1">
  <div class="container">
    <% if ( @show_user.basic && @show_user.basic.is_name? ) %>
      <%= link_to @show_user.basic.name, root_path, class: "navbar-brand #{@color}" %>
    <% end -%>
    <% if ( @show_user.logo && @show_user.logo.reveal? && (@show_user.logo.name.size != 0)) %>
      <%= image_tag @show_user.logo.name.url(:large), height: "50", class: "rounded"%>
    <% end -%>
    <% if @navbar_position == "" %>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% @options.each do |option| %>
            <% unless (option.name == "carousel" || option.name == "contact") %>
              <li class="nav-item">
                <%= link_to "#{option.show}", { controller: "welcomes", action: "#{option.name}" }, class: "nav-link #{@color} #{ action_name == option.name ? 'border-bottom border-secondary' : '' }" %>
              </li>
            <% end -%>
          <% end -%>
        </ul>
      </div>
    <% end -%>
  </div>
</nav>

app/views/shared/_style_left_bar.html.erb
<div class="card">
  <div class="card-body d-flex flex-column">
    <div class="mt-2">
      <%= link_to "头部导航栏背景", background_navbars_path, class: "btn #{ (controller_name == "navbars" && action_name == 'background') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block"%>
    </div>
    <div class="mt-2">
      <%= link_to "头部导航栏字体", color_navbars_path, class: "btn #{ (action_name == 'color') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block"%>
    </div> 
    <div class="mt-2">
      <%= link_to "主页背景", background_basics_path, class: "btn #{ (controller_name == "basics" && action_name == 'background') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block"%>
    </div>
    <% unless current_user.contacts.where(reveal: true).size == 0  %>
      <div class="mt-2">
        <%= link_to current_user.options.find_by(name: "contact").show, contact_basics_path, class: "btn #{ (action_name == 'contact') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block"%>
      </div>
    <% end -%>
    <% unless current_user.maps.size == 0 %>
      <div class="mt-2">
        <%= link_to "首页地图", map_position_basics_path, class: "btn #{ (action_name == 'map_position') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block"%>
      </div>
      <div class="mt-2">
        <%= link_to "地图高度", map_height_basics_path, class: "btn #{ (action_name == 'map_height') ? 'btn-primary' : 'btn-outline-secondary' }  btn-block"%>
      </div>
    <% end -%>
  </div>
</div>