config/routes.rb
Rails.application.routes.draw do
  #api
  mount API::Wechats => '/api'

  constraints(SubdomainRoutes) do 
    root "homepages#index"
  end 

  constraints(!SubdomainRoutes) do
    root 'welcomes#show'
    get 'echo', to: "welcomes#feedback", as: :echo
    get 'present', to: "welcomes#introduction", as: :present
    get 'release', to: "welcomes#article", as: :release
    get 'release/:id', to: "welcomes#press", as: :press
    get 'product', to: "welcomes#service", as: :product
    get 'serve/:id', to: "welcomes#serve", as: :serve
    get 'apply', to: "welcomes#recruit", as: :apply
    get 'invite/:id', to: "welcomes#invite", as: :invite
    get 'plat', to: "welcomes#map", as: :plat
    get 'picture', to: "welcomes#photograph", as: :picture
    get 'staff', to: "welcomes#employee", as: :staff
  end

  resources :admins do
    get 'delete', on: :member
    get 'privileges', on: :member
    put 'update_privilege', on: :member
    get 'search', on: :collection
  end

  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :employees do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end

  resources :carousels do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
    get 'attributes_reveal', on: :member
  end

  resources :contacts, :introductions, :articles, :services, :recruits do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end 

  resources :feedbacks do
    get 'delete', on: :member
  end
  
  resources :navbars do 
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'color', on: :collection
    put 'set_color', on: :collection
    get 'position', on: :collection
    put 'set_position', on: :collection
    get 'modify', on: :collection
    put 'set_modify', on: :collection
    get 'order', on: :collection
    put 'sort', on: :collection
  end

  resources :basics do
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'contact', on: :collection
    put 'set_contact', on: :collection
    get 'map_position', on: :collection
    put 'set_map_position', on: :collection
    get 'map_height', on: :collection
    put 'set_map_height', on: :collection
    put 'set_small_map', on: :collection
  end
  
  resources :options do 
    get 'set_reveal', on: :member
  end

  resources :maps do
    get 'delete', on: :member
    get 'set_weight', on: :member
  end

  resources :photographs do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end
    
  resources :pictures, only: [:create]
  get 'kind/:id', to: "welcomes#kind", as: :kind
  resources :logos do
    get 'reveal', on: :member
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  layout "official"
  before_action :ensure_subdomain
  before_action :find_options

  def show
    @introduction = @show_user.introductions.where(reveal: true).first
  end

  def feedback
    if @show_user.has_role?(:feedback)
      @feedback = Feedback.new
    else
      redirect_to root_path
    end
  end

  def employee
  end


  def introduction
    if @show_user.has_role?(:introduction)
      @introduction = @show_user.introductions.where(reveal: true).first
    else
      redirect_to root_path
    end
  end

  def article
    if @show_user.has_role?(:article)
      @releases = @show_user.articles.where(reveal: true).page(params[:page])
    else
      redirect_to root_path
    end
  end

  def photograph
    if @show_user.has_role?(:photograph)
      @photographs = @show_user.photographs.where(reveal: true).page(params[:page])
    else
      redirect_to root_path
    end
  end 

  #set /release/:id
  def press
    if @show_user.has_role?(:article)
      @release = @show_user.articles.where(reveal: true).find(params[:id])
    else
      redirect_to root_path
    end
  end

  def service
    if @show_user.has_role?(:service)
      @services = @show_user.services.where(reveal: true).page(params[:page])
    else
      redirect_to root_path
    end
  end

  #set /service/:id
  def serve
    if @show_user.has_role?(:service)
      @service = @show_user.services.where(reveal: true).find(params[:id])
    else
      redirect_to root_path
    end
  end

  def recruit
    if @show_user.has_role?(:recruit)
      @recruits = @show_user.recruits.where(reveal: true).order("updated_at desc").page(params[:page])
    else
      redirect_to root_path
    end
  end

  #set /recruit/:id
  def invite
    if @show_user.has_role?(:recruit)
      @recruit = @show_user.recruits.where(reveal: true).find(params[:id])
    else
      redirect_to root_path
    end
  end
  
  def map
    if @show_user.has_role?(:map)
      @map = @show_user.maps.first
    else
      redirect_to root_path
    end 
  end

  private
    def ensure_subdomain
      @show_user ||= User.find_by(subdomain: request.subdomain)
      @contact = @show_user.contacts.where(reveal: true).first
      set_meta_tags(title: @show_user.basic.name, keywords: @show_user.basic.keywords, description: @show_user.basic.description)
      redirect_to root_url(subdomain: nil) unless @show_user.present?
    end

    def find_options
      @available_roles = @show_user.roles.reject{ |role| (role == :user) || (role == :root_admin) }.map(&:to_s)
      @options = @show_user.options.where(name: @available_roles).where(reveal: true).order(:position)
      if @show_user.options.find_by(name: "carousel")
        @carousel_option = @show_user.options.find_by(name: "carousel").reveal
      end
      @carousels = @show_user.carousels.where(reveal: true)
      if @carousels.size == 0
        @carousels = nil
      end
      @map = @show_user.maps.first
      @background = @show_user.navbar.background
      @color = @show_user.navbar.color
      @basic_background = @show_user.basic.background
      @navbar_position = @show_user.navbar.position
      @basic_contact = @show_user.basic.contact
      @basic_map_position = @show_user.basic.map_position
      @basic_small_map = @show_user.basic.small_map
    end
end

app/views/welcomes/article.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <% @releases.each_with_index do |release, index| %>
      <div class="d-flex justify-content-between text-secondary">
        <div>
          <%= params[:page] ? (index + 1 + (params[:page].to_i-1)*10) : (index+1) %>.
          <%= link_to release.title, press_path(release), class: "text-secondary" %>
        </div>
        <div class="small text-secondary">
          <%= release.updated_at.strftime("%F") %>
        </div>
      </div>
    <% end %>
    <div class="mt-2">
      <div><%= paginate @releases %></div>
    </div>  
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>

app/views/welcomes/feedback.html.erb
<% provide(:title, @show_user.basic.name) %>
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <%= form_with(model: @feedback, local: true) do |form| %>
      <div class="form-group">
        <%= form.text_field :name, placeholder: "联系方式, 手机号码或邮箱", class: "form-control #{'is-invalid' if has_error?(@feedback, :name)}" %>
        <% if has_error?(@feedback, :name) %>
          <div class="invalid-feedback d-block"><%= get_error(@feedback, :name) %></div>
        <% end -%>
      </div>

      <div class="form-group">
        <%= form.text_area :content, placeholder: "评论内容", rows: "5", class: "form-control #{'is-invalid' if has_error?(@feedback, :content)}" %>
        <% if has_error?(@feedback, :content) %>
          <div class="invalid-feedback d-block"><%= get_error(@feedback, :content) %></div>
        <% end -%>
      </div>

      <div class="form-group d-flex <%= @contact == 'right' ? '' : 'flex-row-reverse' %>">
        <%= form.submit "创建评论", class: "btn btn-primary" %>
      </div>
    <% end -%> 
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>

app/views/welcomes/introduction.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %> " id="picture">
    <div class="card">
      <div class="card-body">
        <div id="picture">
          <%= markdown @introduction.content if @introduction %>
        </div>  
      </div>
    </div>
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>
<%= render 'shared/simplemde_style' %>

app/views/welcomes/invite.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <div class="card">
      <div class="card-header text-secondary text-center"><%= @recruit.title %></div>
      <div class="card-body">
        <div class="text-secondary text-center">
          <p><small>
            <i class="fa fa-user fa-fw"></i><%= @recruit.user.email.split("@").first %>
            · 发表于<%= time_ago_in_words(@recruit.created_at) %>前
          </small></p>
        </div>
        <div id="picture">
          <%= markdown @recruit.content if @recruit %>
        </div>
      </div>
    </div>
    <div class="mt-2"><%= link_to "返回", apply_path, class: "btn btn-primary" %></div>
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>
<%= render 'shared/simplemde_style' %>

app/views/welcomes/map.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <% if @map %>
      <%= render 'shared/big_map' %>
    <% end -%>
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>

app/views/welcomes/press.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <div class="card">
      <div class="card-header text-secondary text-center"><%= @release.title %></div>
      <div class="card-body">
        <div class="text-secondary text-center">
          <p><small>
            <i class="fa fa-user fa-fw"></i><%= @release.user.email.split("@").first %>
            · 发表于<%= time_ago_in_words(@release.created_at) %>前
          </small></p>
        </div>
        <div id="picture">
          <%= markdown @release.content  if @release %>
        </div>
      </div>
    </div>
    <div class="mt-2"><%= link_to "返回", release_path, class: "btn btn-primary" %></div>
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>
<%= render 'shared/simplemde_style' %>

app/views/welcomes/recruit.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <% @recruits.each_with_index do |recruit, index| %>
      <div class="d-flex justify-content-between text-secondary">
        <div>
          <%= params[:page] ? (index + 1 + (params[:page].to_i-1)*10) : (index+1) %>.
          <%= link_to recruit.title, invite_path(recruit), class: "text-secondary" %>
        </div>
        <div class="small text-secondary">
          <%= recruit.updated_at.strftime("%F") %>
        </div>
      </div>
    <% end %>
    <div class="mt-2">
      <div><%= paginate @recruits %></div>
    </div>  
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>

app/views/welcomes/serve.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <div class="card">
      <div class="card-header text-secondary text-center"><%= @service.name %></div>
      <div class="card-body">
        <div class="text-secondary text-center">
          <p><small>
            <i class="fa fa-user fa-fw"></i><%= @service.user.email.split("@").first %>
            · 发表于<%= time_ago_in_words(@service.created_at) %>前
          </small></p>
        </div>
        <div id="picture">
          <%= markdown @service.description  if @service %>
        </div>
      </div>
    </div>
    <div class="mt-2"><%= link_to "返回", product_path, class: "btn btn-primary" %></div>
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>
<%= render 'shared/simplemde_style' %>

app/views/welcomes/service.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <% @services.each_with_index do |service, index| %>
      <div class="d-flex justify-content-between">
        <div class="text-secondary">
          <%= params[:page] ? (index + 1 + (params[:page].to_i-1)*10) : (index+1) %>.
          <%= link_to service.name, serve_path(service), class: "text-secondary" %>
        </div>
        <div class="small text-secondary">
          <%= service.updated_at.strftime("%F") %>
        </div>
      </div>
    <% end %>
    <div class="d-flex mt-2">
      <div><%= paginate @services %></div>
    </div> 
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>

app/views/welcomes/show.html.erb
<div class="mb-2">
  <%= render 'shared/show_middle' %>
</div>
<div class="row">
  <% if @basic_contact == "left" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
  <div class="<%= @basic_contact == '' ? 'col-md-12' : 'col-md-9' %>">
    <div class="card mb-2">
      <div class="card-body">
        <div id="picture">
          <%= markdown @introduction.content if @introduction %>
        </div>
      </div>
    </div>
    <% if ((@basic_map_position == "right") && @map) %>
      <%= render 'shared/big_map' %>
    <% end -%>
  </div>
  <% if @basic_contact == "right" %>
    <div class="col-md-3"><%= render 'shared/contact' %></div>
  <% end -%>
</div>
<%= render 'shared/simplemde_style' %>