config/routes.rb
Rails.application.routes.draw do
  #api
  mount API::Wechats => '/api'

  constraints(SubdomainRoutes) do 
    root "homepages#index"
  end 

  constraints(!SubdomainRoutes) do
    root 'welcomes#show'
    get 'echo', to: "welcomes#feedback", as: :echo
    get 'present', to: "welcomes#introduction", as: :present
    get 'release', to: "welcomes#article", as: :release
    get 'release/:id', to: "welcomes#press", as: :press
    get 'product', to: "welcomes#service", as: :product
    get 'serve/:id', to: "welcomes#serve", as: :serve
    get 'apply', to: "welcomes#recruit", as: :apply
    get 'invite/:id', to: "welcomes#invite", as: :invite
    get 'plat', to: "welcomes#map", as: :plat
    get 'picture', to: "welcomes#photograph", as: :picture
    get 'staff', to: "welcomes#employee", as: :staff
  end

  resources :admins do
    get 'delete', on: :member
    get 'privileges', on: :member
    put 'update_privilege', on: :member
    get 'search', on: :collection
  end

  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :employees do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end

  resources :carousels do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
    get 'attributes_reveal', on: :member
  end

  resources :contacts, :introductions, :articles, :services, :recruits do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end 

  resources :feedbacks do
    get 'delete', on: :member
  end
  
  resources :navbars do 
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'color', on: :collection
    put 'set_color', on: :collection
    get 'position', on: :collection
    put 'set_position', on: :collection
    get 'modify', on: :collection
    put 'set_modify', on: :collection
    get 'order', on: :collection
    put 'sort', on: :collection
  end

  resources :basics do
    get 'background', on: :collection
    put 'set_background', on: :collection
    get 'contact', on: :collection
    put 'set_contact', on: :collection
    get 'map_position', on: :collection
    put 'set_map_position', on: :collection
    get 'map_height', on: :collection
    put 'set_map_height', on: :collection
    put 'set_small_map', on: :collection
  end
  
  resources :options do 
    get 'set_reveal', on: :member
  end

  resources :maps do
    get 'delete', on: :member
    get 'set_weight', on: :member
  end

  resources :photographs do
    get 'delete', on: :member
    get 'set_weight', on: :member
    get 'set_reveal', on: :member
  end
    
  resources :pictures, only: [:create]
  get 'kind/:id', to: "welcomes#kind", as: :kind
  resources :logos do
    get 'reveal', on: :member
  end
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  belongs_to :user, optional: true

  default_scope { order("weight desc") }

  validates :title, presence: { message: "标题不能为空" }
  validates :content, presence: { message: "内容不能为空" }
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recruit, only: [:show, :edit, :update, :destroy, :delete, :set_weight, :set_reveal]
  before_action :set_recruits, only: [:index, :set_weight, :set_reveal]
  before_action :set_left_bar
  access recruit: :all, message: "当前用户无权访问"

  # GET /recruits
  def index
  end

  def set_reveal
    @recruit.toggle!(:reveal)
    respond_to do |format|
      format.js do
      end
    end
  end

  def set_weight
    @recruit.update(weight: Time.now)
    respond_to do |format|
      format.js do
      end
    end
  end

  # GET /recruits/1
  def show
  end

  # GET /recruits/new
  def new
    @recruit = current_user.recruits.new
  end

  # GET /recruits/1/edit
  def edit
  end

  # POST /recruits
  def create
    @recruit = current_user.recruits.new(recruit_params)

    if @recruit.save
      flash[:success] = "创建成功"
      redirect_to recruits_path
    else
      render :new
    end
  end

  # PATCH/PUT /recruits/1
  def update
    if @recruit.update(recruit_params)
      flash[:success] = "更新成功"
      redirect_to recruits_path
    else
      render :edit
    end
  end


  def delete
  end

  # DELETE /recruits/1
  def destroy
    @recruit.destroy
    flash[:success] = "删除成功"
    redirect_to recruits_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruit
      @recruit = current_user.recruits.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recruit_params
      params.require(:recruit).permit(:title, :content)
    end

    def set_recruits
      @recruits = current_user.recruits.page(params[:page])
    end

    def set_left_bar
      @available_roles = current_user.roles.reject{ |role| (role == :user) || (role == :root_admin) }.map(&:to_s)
      @options = current_user.options.where(name: @available_roles).where(reveal: true).order(:position)
    end
end

app/views/recruits/_delete.html.erb
<button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">取消</button>
<%= link_to "确定", recruit_path(@recruit), class: "btn btn-sm btn-danger", remote: true, method: :delete %>

app/views/recruits/_form.html.erb
<%= form_with(model: recruit, local: true) do |form| %>
  <% unless recruit.errors.blank? %>
    <div class="alert alert-danger">
      <ul class="list-unstyled">
        <% recruit.errors.messages.values.flatten.each do |error| %>
          <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
        <% end -%>
      </ul>
    </div>
  <% end -%>

  <div class="form-group">
    <%= form.text_field :title, placeholder: "输入标题", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.text_area :content, placeholder: "输入内容", class: "form-control simplemde" %>
  </div>
  
  <div class="form-group">
    <%= form.submit recruit.new_record?  ? "新建" : "更新", class: "btn btn-primary" %>
  </div> 
<% end %>

<%= content_for :javascripts do %>
  <script>
    $(function () {
      document.querySelectorAll('.simplemde').forEach(function(editor) {
        var simplemde = new SimpleMDE({
          promptURLs: true,
          element: editor });

        inlineAttachment.editors.codemirror4.attach(simplemde.codemirror, {
          uploadUrl: '/pictures',
          extraHeaders: { 'X-CSRF-Token': Rails.csrfToken() }
        });
      });
    })
  </script>
<% end -%>

app/views/recruits/_recruits.html.erb
<div id="recruits">
  <% @recruits.each_with_index do |recruit, index| %>
    <div class="d-flex justify-content-between">
      <div>
        <%= params[:page] ? (index + 1 + (params[:page].to_i-1)*10) : (index+1) %>.
        <%= recruit.title %>
        <% if @recruits.first == recruit %>
          <span class="badge badge-danger">已置顶</span>
        <% end -%>
        <% if recruit.reveal? %>
          <span class="badge badge-danger">已显示</span>
        <% else %>
          <span class="badge badge-primary">已隐藏</span>
        <% end -%>
      </div>
      <div>
        <%= link_to "查看", recruit_path(recruit), class: "badge badge-primary" %>
        <% unless @recruits.first == recruit %>
          <%= link_to "置顶", set_weight_recruit_path(recruit), remote: true, class: "badge badge-primary" %>
        <% end -%> 
        <%= link_to '编辑', edit_recruit_path(recruit), class: "badge badge-primary" %>
        <%= link_to '删除', delete_recruit_path(recruit), remote: true, class: "badge badge-primary" %>
        <%= link_to recruit.reveal? ? "隐藏" : "显示", set_reveal_recruit_path(recruit), remote: true, class: "badge badge-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/recruits/edit.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/left_bar' %></div>
  <div class="col-md-9">
    <%= render 'form', recruit: @recruit %>
  </div>
</div>

app/views/recruits/index.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/left_bar' %></div>
  <div class="col-md-9">
    <div id="recruits">
      <%= render 'recruits' %>
    </div>
    <div class="d-flex justify-content-between mt-2">
      <div><%= link_to '新建', new_recruit_path, class: "btn btn-primary" %></div>
      <div><%= paginate @recruits %></div>
    </div>
  </div>
</div>
<%= render 'shared/confirm_modal' %>

app/views/recruits/new.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/left_bar' %></div>
  <div class="col-md-9">
    <%= render 'form', recruit: @recruit %>
  </div>
</div>

app/views/recruits/set_reveal.js.erb
$('#recruits').replaceWith('<%= j render "recruits" %>');
toastr['success']('设置成功!');

app/views/recruits/set_weight.js.erb
$('#recruits').replaceWith('<%= j render "recruits" %>');
toastr['success']('置顶成功!');

app/views/recruits/show.html.erb
<%= render 'shared/nav' %>
<div class="row">
  <div class="col-md-3"><%= render 'shared/left_bar' %></div>
  <div class="col-md-9">
    <div class="card mb-3">
      <div class="card-header text-secondary text-center"><%= @recruit.title %></div>
      <div class="card-body">
        <div class="text-secondary text-center">
          <p><small>
            <i class="fa fa-user fa-fw"></i><%= @recruit.user.email.split("@").first %>
            · 发表于<%= time_ago_in_words(@recruit.created_at) %>前
          </small></p>
        </div>
        <div class="text-secondary" id="picture"><%= markdown @recruit.content %></div>
      </div>
    </div> 
    <div><%= link_to "返回列表", recruits_path, class: "btn btn-primary" %></div>
  </div>
</div>
<%= render 'shared/simplemde_style' %>